// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnFscNmfhD1vC_gz_fCyGB3UdNsLp8F8',
    appId: '1:466365343558:android:4b1777ad090c6f3442e747',
    messagingSenderId: '466365343558',
    projectId: 'hotelregistration1',
    databaseURL: 'https://hotelregistration1-default-rtdb.firebaseio.com',
    storageBucket: 'hotelregistration1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIeDql347lYtkkHCLv6SGvAtk0bHRyHug',
    appId: '1:466365343558:ios:56b2449b2ee4a52642e747',
    messagingSenderId: '466365343558',
    projectId: 'hotelregistration1',
    databaseURL: 'https://hotelregistration1-default-rtdb.firebaseio.com',
    storageBucket: 'hotelregistration1.appspot.com',
    iosClientId: '466365343558-fok99pt61na1eq67d0t2ocflquitd7t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelRegistration',
  );
}
